name: taxcalc-dev
channels:
  - conda-forge
dependencies:
- python
- "numpy>=1.14"
- "pandas>=1.1.0"
- "bokeh>=1.4.0"
- requests
- numba
- pytest
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- "paramtools>=0.14.2"
- pip
- pip:
    - jupyter-book
